In [1]:
import os

import datasets
import pandas as pd

In [2]:
dataset = datasets.load_dataset('snegha24/Tamil_tnpscExam')

In [3]:
dataset.save_to_disk('../files/tnpsc')

Saving the dataset (0/1 shards):   0%|          | 0/516 [00:00<?, ? examples/s]

In [4]:
df = pd.DataFrame(dataset['train'])
df

,language,country,file_name,source,license,level,category_en,category_original_lang,original_question_num,question,options,answer
0,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,104,எபிதீலியல்‌ செல்லில்‌ புற்றுநோய்‌ உருவாவதற்கு ...,"[லூக்கோமியா, சார்க்கோமா, கார்சினோமா, லிப்போமா]",3
1,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,108,பொருந்தாததைக்‌ கண்டுபிடி.,"[இளஞ்சேட்சென்னி, கோச்செங்கணான்‌, பெருஞ்சேரல்‌ ...",3
2,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,111,தமிழ்நாட்டின்‌ முதல்‌ பெண்‌ மருத்துவர்‌ யார்‌?,"[மூவலூர்‌ ராமாமிர்தம்‌, முத்துலெட்சுமி ரெட்டி,...",2
3,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,112,பின்வருவனவற்றுள்‌ எந்த சபை இரட்டைமலை சீனிவாசனா...,"[சாக்கிய பெளத்த சங்கம்‌, அத்வைதானந்த சபா, அகில...",4
4,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,137,பின்வரும்‌ சட்டப்‌ பிரிவுகளில்‌ எந்தச்‌ சட்டப்...,"[சட்டப்பிரிவு 23 மற்றும்‌ 226, சட்டப்பிரிவு 32...",4
...,...,...,...,...,...,...,...,...,...,...,...,...
511,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,190,"ஒரு கணக்கெடுப்பில், மொத்த மக்கள்தொகையில் ஒவ்வொ...","[முழுக்கணிப்பு, இரண்டாம் நிலை தரவுகள், வினா தொ...",1
512,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,191,"4 % ஆண்டு வட்டி வீதப்படி 2 ஆண்டுகளில் ரூ. 1,63...","[Rs. 10,000, Rs. 20,000, Rs. 30,000, Rs. 40,000]",2
513,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,171,2011 மக்கட்தொகை கணக்கெடுப்பின்படி தமிழ்நாட்டின...,"[555 மக்கள் / ச.கி.மீ., 480 மக்கள் / ச.கி.மீ, ...",1
514,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,172,கிரீன்விச் தீர்க்கரேகையில் மதியம் 1 மணியாக உள்...,"[4.30 pm, 5.30 pm, 6.30 pm, 7.30 pm]",3
515,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,195,ஒரு செவ்வகத்தின் நீளம் 50% அளவிற்கு குறைத்தும்...,"[10% குறைவாக, 10% அதிகமாக, 20% குறைவாக, 20% அத...",1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 516 entries, 0 to 515
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   language                516 non-null    object
 1   country                 516 non-null    object
 2   file_name               516 non-null    object
 3   source                  516 non-null    object
 4   license                 516 non-null    object
 5   level                   516 non-null    object
 6   category_en             516 non-null    object
 7   category_original_lang  516 non-null    object
 8   original_question_num   516 non-null    object
 9   question                516 non-null    object
 10  options                 516 non-null    object
 11  answer                  516 non-null    object
dtypes: object(12)
memory usage: 48.5+ KB

In [6]:
df['answer'] = df['answer'].astype(str)

In [7]:
def extract_ans_from_list(series):
    try:
        ans_index = int(series['answer'])
        series['answer'] = series['options'][ans_index - 1]
    except:
        pass
    return series

In [8]:
df = df.apply(extract_ans_from_list, axis=1)
df

,language,country,file_name,source,license,level,category_en,category_original_lang,original_question_num,question,options,answer
0,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,104,எபிதீலியல்‌ செல்லில்‌ புற்றுநோய்‌ உருவாவதற்கு ...,"[லூக்கோமியா, சார்க்கோமா, கார்சினோமா, லிப்போமா]",கார்சினோமா
1,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,108,பொருந்தாததைக்‌ கண்டுபிடி.,"[இளஞ்சேட்சென்னி, கோச்செங்கணான்‌, பெருஞ்சேரல்‌ ...",பெருஞ்சேரல்‌ இரும்பொறை
2,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,111,தமிழ்நாட்டின்‌ முதல்‌ பெண்‌ மருத்துவர்‌ யார்‌?,"[மூவலூர்‌ ராமாமிர்தம்‌, முத்துலெட்சுமி ரெட்டி,...",முத்துலெட்சுமி ரெட்டி
3,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,112,பின்வருவனவற்றுள்‌ எந்த சபை இரட்டைமலை சீனிவாசனா...,"[சாக்கிய பெளத்த சங்கம்‌, அத்வைதானந்த சபா, அகில...",ஆதி திராவிட மகாஜன சபை
4,ta,India,tnpsc-group-4-2022-paper-general-studies.pdf,https://freeebook.jagranjosh.com/free-pdf-page...,open,University,Governement Exam,அரசு தேர்வு,137,பின்வரும்‌ சட்டப்‌ பிரிவுகளில்‌ எந்தச்‌ சட்டப்...,"[சட்டப்பிரிவு 23 மற்றும்‌ 226, சட்டப்பிரிவு 32...",சட்டப்பிரிவு 32 மற்றும்‌ 226
...,...,...,...,...,...,...,...,...,...,...,...,...
511,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,190,"ஒரு கணக்கெடுப்பில், மொத்த மக்கள்தொகையில் ஒவ்வொ...","[முழுக்கணிப்பு, இரண்டாம் நிலை தரவுகள், வினா தொ...",முழுக்கணிப்பு
512,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,191,"4 % ஆண்டு வட்டி வீதப்படி 2 ஆண்டுகளில் ரூ. 1,63...","[Rs. 10,000, Rs. 20,000, Rs. 30,000, Rs. 40,000]","Rs. 20,000"
513,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,171,2011 மக்கட்தொகை கணக்கெடுப்பின்படி தமிழ்நாட்டின...,"[555 மக்கள் / ச.கி.மீ., 480 மக்கள் / ச.கி.மீ, ...",555 மக்கள் / ச.கி.மீ.
514,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,172,கிரீன்விச் தீர்க்கரேகையில் மதியம் 1 மணியாக உள்...,"[4.30 pm, 5.30 pm, 6.30 pm, 7.30 pm]",6.30 pm
515,ta,India,TNPSC Group 2 2015 Question Paper-General Stud...,https://www.tnpscjob.com/tnpsc-group-2-previou...,open,University,Governement Exam,அரசு தேர்வு,195,ஒரு செவ்வகத்தின் நீளம் 50% அளவிற்கு குறைத்தும்...,"[10% குறைவாக, 10% அதிகமாக, 20% குறைவாக, 20% அத...",10% குறைவாக

# RAG

In [9]:
from langchain_community.vectorstores import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
from dotenv import load_dotenv
import os
load_dotenv()

True

In [10]:
docs = []

for i, row in df.iterrows():
    docs.append(
        Document(
            page_content=row['question'],
            metadata={'options': ", ".join(row['options']),
                      'answer':row['answer'],
                      'original_question_num': row['original_question_num'],
                      "link": row['source'],
                      'question_asked_paper':row['file_name']
                      },
        )
    )

## Embedding

In [11]:
embedding = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
embedding

HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2', cache_folder=None, model_kwargs={}, encode_kwargs={}, query_encode_kwargs={}, multi_process=False, show_progress=False)

## VECTOR DATABASE

In [12]:
vector_db = Chroma().from_documents(docs,embedding=embedding,collection_name='TNPSC',persist_directory="./chroma_exam_db")

C:\Users\PC\AppData\Local\Temp\ipykernel_9032\2241201849.py:1: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-chroma package and should be used instead. To use it run `pip install -U `langchain-chroma` and import as `from `langchain_chroma import Chroma``.
  vector_db = Chroma().from_documents(docs,embedding=embedding,collection_name='TNPSC',persist_directory="./chroma_exam_db")

In [37]:
responses = vector_db.similarity_search_with_score('எபிதீலியல்‌ செல்லில்‌ புற்றுநோய்‌ உருவாவதற்கு ________ என்று பெயர்‌.',k=10)

In [64]:
for index in range(len(responses)):
    print(responses[index])

(Document(metadata={'question_asked_paper': 'tnpsc-group-4-2022-paper-general-studies.pdf', 'answer': 'கார்சினோமா', 'original_question_num': '104', 'options': 'லூக்கோமியா, சார்க்கோமா, கார்சினோமா, லிப்போமா', 'link': 'https://freeebook.jagranjosh.com/free-pdf-page?file=tnpsc-group-4-2022-paper-general-studies.pdf'}, page_content='எபிதீலியல்\u200c செல்லில்\u200c புற்றுநோய்\u200c உருவாவதற்கு ________ என்று பெயர்\u200c.'), 2.6635071643903163e-13)
(Document(metadata={'link': 'https://freeebook.jagranjosh.com/free-pdf-page?file=tnpsc-group-4-2022-paper-general-studies.pdf', 'options': 'லூக்கோமியா, சார்க்கோமா, கார்சினோமா, லிப்போமா', 'original_question_num': '104', 'answer': 'கார்சினோமா', 'question_asked_paper': 'tnpsc-group-4-2022-paper-general-studies.pdf'}, page_content='எபிதீலியல்\u200c செல்லில்\u200c புற்றுநோய்\u200c உருவாவதற்கு ________ என்று பெயர்\u200c.'), 2.6635071643903163e-13)
(Document(metadata={'question_asked_paper': 'tnpsc-group-4-2022-paper-general-studies.pdf', 'link': 'https://freeebook.jagranjosh.com/free-pdf-page?file=tnpsc-group-4-2022-paper-general-studies.pdf', 'options': 'லூக்கோமியா, சார்க்கோமா, கார்சினோமா, லிப்போமா', 'answer': 'கார்சினோமா', 'original_question_num': '104'}, page_content='எபிதீலியல்\u200c செல்லில்\u200c புற்றுநோய்\u200c உருவாவதற்கு ________ என்று பெயர்\u200c.'), 2.6635071643903163e-13)
(Document(metadata={'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'options': 'நீதி நெறி கோவை, அறம் பாடும் கோவை, அறவுரைக் கோவை, நல்வழிக் கோவை', 'answer': 'அறவுரைக் கோவை', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view', 'original_question_num': '34'}, page_content="'முதுமொழிக் காஞ்சி' என்று நூலுக்கு வழங்கப்படும் வேறு பெயரினைக் கண்டறிக."), 0.4297751784324646)
(Document(metadata={'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'answer': 'அறவுரைக் கோவை', 'original_question_num': '34', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view', 'options': 'நீதி நெறி கோவை, அறம் பாடும் கோவை, அறவுரைக் கோவை, நல்வழிக் கோவை'}, page_content="'முதுமொழிக் காஞ்சி' என்று நூலுக்கு வழங்கப்படும் வேறு பெயரினைக் கண்டறிக."), 0.4297751784324646)
(Document(metadata={'answer': 'அறவுரைக் கோவை', 'options': 'நீதி நெறி கோவை, அறம் பாடும் கோவை, அறவுரைக் கோவை, நல்வழிக் கோவை', 'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'original_question_num': '34', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view'}, page_content="'முதுமொழிக் காஞ்சி' என்று நூலுக்கு வழங்கப்படும் வேறு பெயரினைக் கண்டறிக."), 0.4297751784324646)
(Document(metadata={'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view', 'answer': 'இகழ்', 'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'options': 'இகழ்ந்து, இகழ்ந்த, இகழ், இகழ்தல்', 'original_question_num': '10'}, page_content="'இகழ்ந்தனர்' என்ற சொல்லின் வேர்ச்சொல்லை எழுதுக."), 0.5016518235206604)
(Document(metadata={'answer': 'இகழ்', 'original_question_num': '10', 'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view', 'options': 'இகழ்ந்து, இகழ்ந்த, இகழ், இகழ்தல்'}, page_content="'இகழ்ந்தனர்' என்ற சொல்லின் வேர்ச்சொல்லை எழுதுக."), 0.5016518235206604)
(Document(metadata={'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'original_question_num': '10', 'answer': 'இகழ்', 'options': 'இகழ்ந்து, இகழ்ந்த, இகழ், இகழ்தல்', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view'}, page_content="'இகழ்ந்தனர்' என்ற சொல்லின் வேர்ச்சொல்லை எழுதுக."), 0.5016518235206604)
(Document(metadata={'options': 'முழுக்கணிப்பு, இரண்டாம் நிலை தரவுகள், வினா தொகுதி, தரவு சேகரிக்கும் முறை', 'original_question_num': '190', 'link': 'https://www.tnpscjob.com/tnpsc-group-2-previous-year-question-papers/', 'question_asked_paper': 'TNPSC Group 2 2015 Question Paper-General Studies.pdf', 'answer': 'முழுக்கணிப்பு'}, page_content='ஒரு கணக்கெடுப்பில், மொத்த மக்கள்தொகையில் ஒவ்வொருவரிடமிருந்தும் விவரங்களைச் சேகரிப்பதற்கு பெயர்'), 0.5075258612632751)

In [57]:
responses

[(Document(metadata={'question_asked_paper': 'tnpsc-group-4-2022-paper-general-studies.pdf', 'answer': 'கார்சினோமா', 'original_question_num': '104', 'options': 'லூக்கோமியா, சார்க்கோமா, கார்சினோமா, லிப்போமா', 'link': 'https://freeebook.jagranjosh.com/free-pdf-page?file=tnpsc-group-4-2022-paper-general-studies.pdf'}, page_content='எபிதீலியல்\u200c செல்லில்\u200c புற்றுநோய்\u200c உருவாவதற்கு ________ என்று பெயர்\u200c.'),
  2.6635071643903163e-13),
 (Document(metadata={'link': 'https://freeebook.jagranjosh.com/free-pdf-page?file=tnpsc-group-4-2022-paper-general-studies.pdf', 'options': 'லூக்கோமியா, சார்க்கோமா, கார்சினோமா, லிப்போமா', 'original_question_num': '104', 'answer': 'கார்சினோமா', 'question_asked_paper': 'tnpsc-group-4-2022-paper-general-studies.pdf'}, page_content='எபிதீலியல்\u200c செல்லில்\u200c புற்றுநோய்\u200c உருவாவதற்கு ________ என்று பெயர்\u200c.'),
  2.6635071643903163e-13),
 (Document(metadata={'question_asked_paper': 'tnpsc-group-4-2022-paper-general-studies.pdf', 'link': 'https://freeebook.jagranjosh.com/free-pdf-page?file=tnpsc-group-4-2022-paper-general-studies.pdf', 'options': 'லூக்கோமியா, சார்க்கோமா, கார்சினோமா, லிப்போமா', 'answer': 'கார்சினோமா', 'original_question_num': '104'}, page_content='எபிதீலியல்\u200c செல்லில்\u200c புற்றுநோய்\u200c உருவாவதற்கு ________ என்று பெயர்\u200c.'),
  2.6635071643903163e-13),
 (Document(metadata={'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'options': 'நீதி நெறி கோவை, அறம் பாடும் கோவை, அறவுரைக் கோவை, நல்வழிக் கோவை', 'answer': 'அறவுரைக் கோவை', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view', 'original_question_num': '34'}, page_content="'முதுமொழிக் காஞ்சி' என்று நூலுக்கு வழங்கப்படும் வேறு பெயரினைக் கண்டறிக."),
  0.4297751784324646),
 (Document(metadata={'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'answer': 'அறவுரைக் கோவை', 'original_question_num': '34', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view', 'options': 'நீதி நெறி கோவை, அறம் பாடும் கோவை, அறவுரைக் கோவை, நல்வழிக் கோவை'}, page_content="'முதுமொழிக் காஞ்சி' என்று நூலுக்கு வழங்கப்படும் வேறு பெயரினைக் கண்டறிக."),
  0.4297751784324646),
 (Document(metadata={'answer': 'அறவுரைக் கோவை', 'options': 'நீதி நெறி கோவை, அறம் பாடும் கோவை, அறவுரைக் கோவை, நல்வழிக் கோவை', 'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'original_question_num': '34', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view'}, page_content="'முதுமொழிக் காஞ்சி' என்று நூலுக்கு வழங்கப்படும் வேறு பெயரினைக் கண்டறிக."),
  0.4297751784324646),
 (Document(metadata={'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view', 'answer': 'இகழ்', 'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'options': 'இகழ்ந்து, இகழ்ந்த, இகழ், இகழ்தல்', 'original_question_num': '10'}, page_content="'இகழ்ந்தனர்' என்ற சொல்லின் வேர்ச்சொல்லை எழுதுக."),
  0.5016518235206604),
 (Document(metadata={'answer': 'இகழ்', 'original_question_num': '10', 'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view', 'options': 'இகழ்ந்து, இகழ்ந்த, இகழ், இகழ்தல்'}, page_content="'இகழ்ந்தனர்' என்ற சொல்லின் வேர்ச்சொல்லை எழுதுக."),
  0.5016518235206604),
 (Document(metadata={'question_asked_paper': 'TNPSC Group 2 2022 Question Paper-Tamil.pdf', 'original_question_num': '10', 'answer': 'இகழ்', 'options': 'இகழ்ந்து, இகழ்ந்த, இகழ், இகழ்தல்', 'link': 'https://drive.google.com/file/d/150sCFtxeC3PMLeZix1-LhpfMXl5O-moH/view'}, page_content="'இகழ்ந்தனர்' என்ற சொல்லின் வேர்ச்சொல்லை எழுதுக."),
  0.5016518235206604),
 (Document(metadata={'options': 'முழுக்கணிப்பு, இரண்டாம் நிலை தரவுகள், வினா தொகுதி, தரவு சேகரிக்கும் முறை', 'original_question_num': '190', 'link': 'https://www.tnpscjob.com/tnpsc-group-2-previous-year-question-papers/', 'question_asked_paper': 'TNPSC Group 2 2015 Question Paper-General Studies.pdf', 'answer': 'முழுக்கணிப்பு'}, page_content='ஒரு கணக்கெடுப்பில், மொத்த மக்கள்தொகையில் ஒவ்வொருவரிடமிருந்தும் விவரங்களைச் சேகரிப்பதற்கு பெயர்'),
  0.5075258612632751)]